name: 'Combine libraries'
description: 'Combine the WebRTC static libraries into one using platform specific tools.'
inputs:
  platform:
    description: 'The platform we are building for (android, ios, linux, mac, win).'
    required: true
  builddir:
    description: 'The the ninja build path.'
    required: true
  allowlist:
    description: 'The libraries to copy objects from'
    required: true
    default: "webrtc boringssl protobuf_lite field_trial_default metrics_default"
outputs:
  library:
    description: "Path to generated library."
    value: ${{ steps.combine.outputs.library }}
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: ${{ inputs.builddir }}
      id: combine
      run: |
        set -x

        # Detect library extension.
        platform=${{ inputs.platform }}
        libext="a"
        if [ "${platform}" = "win" ]; then
          libext="lib"
        fi
        libname=libwebrtc_full.${libext}

        # Library allowlist filter
        allowlist=$(echo ${{ inputs.allowlist }}\\.${libext} | sed "s/ /\\\\.${libext}|/g")

        LIBS=$(cat .ninja_log | tr '\t' '\n' | grep -E "^obj/" | grep -E $allowlist | sort -u)
        mkdir $libname
        for l in $LIBS; do cp "$l" $libname; done

        ls -l
        ls -l $libname
        echo "::set-output name=library::${libname}"
